# Generated by Django 5.1.1 on 2024-09-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_street_address2',
            new_name='default_email_address',
        ),
    ]
