# Generated by Django 5.1.1 on 2024-09-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_default_street_address2_userprofile_default_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_street_address1',
            new_name='default_street_address',
        ),
    ]
