# Generated by Django 5.1.1 on 2024-10-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_promocode_order_discount_amount_order_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
