# Generated by Django 5.1.1 on 2024-10-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_stripe_coupon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_coupon_id',
        ),
    ]
